### ISSUE TITLE
Change license to the Boost to allow commercial usage

### ISSUE THREAD

**Issue by ilya-stromberg** [WebDrake/Dgraph#6]
Please change license from GPLv3 to something more liberal like Boost, MIT or BSD to allow commercial usage.

Also, it would be nice to have graph library in Phobos in a future, and in that case module must be under Boost license. In that case somebody can use Dgraph as initial point.

You can contact igraph authors or use Boost Graph Library (BGL) as a initial point.

See also this topic:
http://forum.dlang.org/thread/efglxfvwwrpteujnaehw@forum.dlang.org

**Comment by mleise** [comment]
GPLv3 is fundamentally only concerned with keeping the open source parts of any software open source, so they can still be updated or patched in the spirit of free software, while proprietary parts remain closed source. In praxis the GPLv3 license is satisfied by shipping the application with shared versions of the libraries. That's without going into problematic cases, like using GPLv3 software behind a web front-end.
