### ISSUE TITLE
isVertex not exposed in CachedEdgeList

### ISSUE THREAD

**Issue by peter-thm** [WebDrake/Dgraph#9]
`CachedEdgeList` doesn't expose `isVertex` from `IndexedEdgeList`.
Adding the following to `CachedEdgeList` works:

    bool isVertex(T : size_t)(in T v) @safe const nothrow pure
    {
        return _graph.isVertex(v);
    }

**Comment by WebDrake** [comment]
Nice catch.  That may have been overlooked because there's a private `alias this` inside `CachedEdgeList` which means that calls to `CachedEdgeList.isVertex` succeed within the `dgraph.graph` module, but fail for external calls.  I'll fix shortly.
